name: Test FastAPI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Descargar código
      uses: actions/checkout@v4
      
    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Instalar dependencias
      run: |
        pip install fastapi uvicorn pytest
        
    - name: Correr tests
      run: pytest
